name: Publish mod

on:
  push:
    branches: [ master ]

jobs:
  automaticpublish:
    name: Automatic Mod Browser Publish Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JavidPack/tModLoaderPublishIntegration@v0.11.8.3
        with:
          STEAMID64: ${{ secrets.STEAMID64 }}
          MODBROWSERPASSPHRASE: ${{ secrets.MODBROWSERPASSPHRASE }}
          MODNAME: EchDLC
